# action.yml
name: 'Impilo team utility'
description: 'Get various data about code like vulnerabilities and license usage.'
inputs:
  project-name:
    description: 'Name of the project'
    required: false
    default: 'app'
    type: string
  config-file:
    description: 'Config file. Default: impilo.yml'
    required: false
    default: impilo.yml
    type: string
  ignore-config-file:
    description: 'Ignore any config file'
    required: false
    default: 'true'
    type: boolean
  target-directory:
    description: 'Directory where the project file is found'
    required: false
    default: ''
    type: string
  package-manager:
    description: 'Package manager eg. npm, nuget'
    required: false
    default: 'npm'
    type: string
  scan-vulnerabilities:
    description: 'Vulnerabilities should be scanned'
    required: false
    default: 'true'
    type: boolean
  scan-licenses:
    description: 'Licenses should be scanned'
    required: false
    default: 'true'
    type: boolean
outputs:
  config-file:
    description: 'Foo - remove'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-name }}
    - ${{ inputs.config-file }}
    - ${{ inputs.ignore-config-file }}
    - ${{ inputs.target-directory }}
    - ${{ inputs.package-manager }}
    - ${{ inputs.scan-vulnerabilities }}
    - ${{ inputs.scan-licenses }}